// <auto-generated />
using System;
using Dukkantek_WebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dukkantek_WebAPI.Migrations
{
    [DbContext(typeof(DukkantekDBContext))]
    [Migration("20220423093418_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dukkantek_WebAPI.Entities.ProductCategories", b =>
                {
                    b.Property<int>("ProductCategoriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ProductCategoriesID");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoriesID = 1,
                            Category = "Electronics",
                            IsActive = true
                        },
                        new
                        {
                            ProductCategoriesID = 2,
                            Category = "Fragrances",
                            IsActive = true
                        },
                        new
                        {
                            ProductCategoriesID = 3,
                            Category = "Footwear",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Dukkantek_WebAPI.Entities.ProductSaleStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ProductSaleStatus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Status = "SOLD"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Status = "VOID"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Status = "REFUND"
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            Status = "EXCHANGE"
                        });
                });

            modelBuilder.Entity("Dukkantek_WebAPI.Entities.ProductSales", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ProductSaleStatusID")
                        .HasColumnType("int");

                    b.Property<int>("SaleTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ProductSales");
                });

            modelBuilder.Entity("Dukkantek_WebAPI.Entities.ProductStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ProductStatus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Status = "INSTOCK"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Status = "SOLD"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Status = "DAMAGED"
                        });
                });

            modelBuilder.Entity("Dukkantek_WebAPI.Entities.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStatusID")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Barcode = "48454",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 230, DateTimeKind.Local).AddTicks(545),
                            Description = "This is a description of Product-01",
                            IsActive = true,
                            Name = "Product-01",
                            ProductStatusID = 1,
                            Weight = 12m
                        },
                        new
                        {
                            ID = 2,
                            Barcode = "59646",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(1354),
                            Description = "This is a description of Product-11",
                            IsActive = true,
                            Name = "Product-11",
                            ProductStatusID = 1,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 3,
                            Barcode = "87964",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(1751),
                            Description = "This is a description of Product-21",
                            IsActive = true,
                            Name = "Product-21",
                            ProductStatusID = 2,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 4,
                            Barcode = "34633",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(2017),
                            Description = "This is a description of Product-31",
                            IsActive = true,
                            Name = "Product-31",
                            ProductStatusID = 2,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 5,
                            Barcode = "17540",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(2301),
                            Description = "This is a description of Product-41",
                            IsActive = true,
                            Name = "Product-41",
                            ProductStatusID = 1,
                            Weight = 11m
                        },
                        new
                        {
                            ID = 6,
                            Barcode = "88949",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(2567),
                            Description = "This is a description of Product-51",
                            IsActive = true,
                            Name = "Product-51",
                            ProductStatusID = 1,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 7,
                            Barcode = "79846",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(2813),
                            Description = "This is a description of Product-61",
                            IsActive = true,
                            Name = "Product-61",
                            ProductStatusID = 2,
                            Weight = 12m
                        },
                        new
                        {
                            ID = 8,
                            Barcode = "31766",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(3162),
                            Description = "This is a description of Product-71",
                            IsActive = true,
                            Name = "Product-71",
                            ProductStatusID = 2,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 9,
                            Barcode = "46756",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(3414),
                            Description = "This is a description of Product-81",
                            IsActive = true,
                            Name = "Product-81",
                            ProductStatusID = 1,
                            Weight = 15m
                        },
                        new
                        {
                            ID = 10,
                            Barcode = "77409",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(3658),
                            Description = "This is a description of Product-91",
                            IsActive = true,
                            Name = "Product-91",
                            ProductStatusID = 2,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 11,
                            Barcode = "88551",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(3904),
                            Description = "This is a description of Product-101",
                            IsActive = true,
                            Name = "Product-101",
                            ProductStatusID = 1,
                            Weight = 12m
                        },
                        new
                        {
                            ID = 12,
                            Barcode = "26271",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(4225),
                            Description = "This is a description of Product-111",
                            IsActive = true,
                            Name = "Product-111",
                            ProductStatusID = 2,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 13,
                            Barcode = "83484",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(4478),
                            Description = "This is a description of Product-121",
                            IsActive = true,
                            Name = "Product-121",
                            ProductStatusID = 2,
                            Weight = 15m
                        },
                        new
                        {
                            ID = 14,
                            Barcode = "21049",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(4718),
                            Description = "This is a description of Product-131",
                            IsActive = true,
                            Name = "Product-131",
                            ProductStatusID = 1,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 15,
                            Barcode = "38306",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(4955),
                            Description = "This is a description of Product-141",
                            IsActive = true,
                            Name = "Product-141",
                            ProductStatusID = 1,
                            Weight = 16m
                        },
                        new
                        {
                            ID = 16,
                            Barcode = "83550",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(5192),
                            Description = "This is a description of Product-151",
                            IsActive = true,
                            Name = "Product-151",
                            ProductStatusID = 2,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 17,
                            Barcode = "86919",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(5501),
                            Description = "This is a description of Product-161",
                            IsActive = true,
                            Name = "Product-161",
                            ProductStatusID = 1,
                            Weight = 19m
                        },
                        new
                        {
                            ID = 18,
                            Barcode = "52419",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(5758),
                            Description = "This is a description of Product-171",
                            IsActive = true,
                            Name = "Product-171",
                            ProductStatusID = 2,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 19,
                            Barcode = "66676",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(5998),
                            Description = "This is a description of Product-181",
                            IsActive = true,
                            Name = "Product-181",
                            ProductStatusID = 1,
                            Weight = 15m
                        },
                        new
                        {
                            ID = 20,
                            Barcode = "39927",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(6239),
                            Description = "This is a description of Product-191",
                            IsActive = true,
                            Name = "Product-191",
                            ProductStatusID = 1,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 21,
                            Barcode = "61372",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(6554),
                            Description = "This is a description of Product-201",
                            IsActive = true,
                            Name = "Product-201",
                            ProductStatusID = 1,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 22,
                            Barcode = "44936",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(6796),
                            Description = "This is a description of Product-211",
                            IsActive = true,
                            Name = "Product-211",
                            ProductStatusID = 1,
                            Weight = 14m
                        },
                        new
                        {
                            ID = 23,
                            Barcode = "73627",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(7031),
                            Description = "This is a description of Product-221",
                            IsActive = true,
                            Name = "Product-221",
                            ProductStatusID = 2,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 24,
                            Barcode = "89186",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(7269),
                            Description = "This is a description of Product-231",
                            IsActive = true,
                            Name = "Product-231",
                            ProductStatusID = 2,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 25,
                            Barcode = "23435",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(7505),
                            Description = "This is a description of Product-241",
                            IsActive = true,
                            Name = "Product-241",
                            ProductStatusID = 2,
                            Weight = 14m
                        },
                        new
                        {
                            ID = 26,
                            Barcode = "79455",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(7828),
                            Description = "This is a description of Product-251",
                            IsActive = true,
                            Name = "Product-251",
                            ProductStatusID = 2,
                            Weight = 16m
                        },
                        new
                        {
                            ID = 27,
                            Barcode = "50653",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(8086),
                            Description = "This is a description of Product-261",
                            IsActive = true,
                            Name = "Product-261",
                            ProductStatusID = 1,
                            Weight = 16m
                        },
                        new
                        {
                            ID = 28,
                            Barcode = "48667",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(8333),
                            Description = "This is a description of Product-271",
                            IsActive = true,
                            Name = "Product-271",
                            ProductStatusID = 2,
                            Weight = 19m
                        },
                        new
                        {
                            ID = 29,
                            Barcode = "41567",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(8565),
                            Description = "This is a description of Product-281",
                            IsActive = true,
                            Name = "Product-281",
                            ProductStatusID = 2,
                            Weight = 16m
                        },
                        new
                        {
                            ID = 30,
                            Barcode = "34900",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(8814),
                            Description = "This is a description of Product-291",
                            IsActive = true,
                            Name = "Product-291",
                            ProductStatusID = 1,
                            Weight = 11m
                        },
                        new
                        {
                            ID = 31,
                            Barcode = "44202",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(9051),
                            Description = "This is a description of Product-301",
                            IsActive = true,
                            Name = "Product-301",
                            ProductStatusID = 1,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 32,
                            Barcode = "88462",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(9428),
                            Description = "This is a description of Product-311",
                            IsActive = true,
                            Name = "Product-311",
                            ProductStatusID = 1,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 33,
                            Barcode = "66007",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(9687),
                            Description = "This is a description of Product-321",
                            IsActive = true,
                            Name = "Product-321",
                            ProductStatusID = 2,
                            Weight = 14m
                        },
                        new
                        {
                            ID = 34,
                            Barcode = "60255",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 232, DateTimeKind.Local).AddTicks(9940),
                            Description = "This is a description of Product-331",
                            IsActive = true,
                            Name = "Product-331",
                            ProductStatusID = 2,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 35,
                            Barcode = "57879",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(179),
                            Description = "This is a description of Product-341",
                            IsActive = true,
                            Name = "Product-341",
                            ProductStatusID = 2,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 36,
                            Barcode = "30310",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(431),
                            Description = "This is a description of Product-351",
                            IsActive = true,
                            Name = "Product-351",
                            ProductStatusID = 1,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 37,
                            Barcode = "81397",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(775),
                            Description = "This is a description of Product-361",
                            IsActive = true,
                            Name = "Product-361",
                            ProductStatusID = 2,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 38,
                            Barcode = "45700",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(1128),
                            Description = "This is a description of Product-371",
                            IsActive = true,
                            Name = "Product-371",
                            ProductStatusID = 2,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 39,
                            Barcode = "37492",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(1457),
                            Description = "This is a description of Product-381",
                            IsActive = true,
                            Name = "Product-381",
                            ProductStatusID = 2,
                            Weight = 18m
                        },
                        new
                        {
                            ID = 40,
                            Barcode = "95363",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(1770),
                            Description = "This is a description of Product-391",
                            IsActive = true,
                            Name = "Product-391",
                            ProductStatusID = 1,
                            Weight = 14m
                        },
                        new
                        {
                            ID = 41,
                            Barcode = "98595",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(2217),
                            Description = "This is a description of Product-401",
                            IsActive = true,
                            Name = "Product-401",
                            ProductStatusID = 2,
                            Weight = 12m
                        },
                        new
                        {
                            ID = 42,
                            Barcode = "84215",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(2561),
                            Description = "This is a description of Product-411",
                            IsActive = true,
                            Name = "Product-411",
                            ProductStatusID = 1,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 43,
                            Barcode = "36450",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(2893),
                            Description = "This is a description of Product-421",
                            IsActive = true,
                            Name = "Product-421",
                            ProductStatusID = 2,
                            Weight = 13m
                        },
                        new
                        {
                            ID = 44,
                            Barcode = "30093",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(3146),
                            Description = "This is a description of Product-431",
                            IsActive = true,
                            Name = "Product-431",
                            ProductStatusID = 1,
                            Weight = 10m
                        },
                        new
                        {
                            ID = 45,
                            Barcode = "29208",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(3422),
                            Description = "This is a description of Product-441",
                            IsActive = true,
                            Name = "Product-441",
                            ProductStatusID = 1,
                            Weight = 17m
                        },
                        new
                        {
                            ID = 46,
                            Barcode = "27589",
                            CategoryID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(3750),
                            Description = "This is a description of Product-451",
                            IsActive = true,
                            Name = "Product-451",
                            ProductStatusID = 2,
                            Weight = 11m
                        },
                        new
                        {
                            ID = 47,
                            Barcode = "25035",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(4018),
                            Description = "This is a description of Product-461",
                            IsActive = true,
                            Name = "Product-461",
                            ProductStatusID = 1,
                            Weight = 19m
                        },
                        new
                        {
                            ID = 48,
                            Barcode = "32062",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(4280),
                            Description = "This is a description of Product-471",
                            IsActive = true,
                            Name = "Product-471",
                            ProductStatusID = 2,
                            Weight = 12m
                        },
                        new
                        {
                            ID = 49,
                            Barcode = "50950",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(4538),
                            Description = "This is a description of Product-481",
                            IsActive = true,
                            Name = "Product-481",
                            ProductStatusID = 2,
                            Weight = 19m
                        },
                        new
                        {
                            ID = 50,
                            Barcode = "14160",
                            CategoryID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2022, 4, 23, 14, 34, 17, 233, DateTimeKind.Local).AddTicks(4858),
                            Description = "This is a description of Product-491",
                            IsActive = true,
                            Name = "Product-491",
                            ProductStatusID = 2,
                            Weight = 14m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
